version: '3'
services:

  # Application
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: .
      dockerfile: app/app.dockerfile
    working_dir: /var/www/ba-sulu-intranet
    volumes:
      - ..:/var/www/ba-sulu-intranet
      - ./app/php.ini:/usr/local/etc/php/php.ini
    links:
      - database:database
    environment:
      - "DATABASE_HOST=database"
      - "DATABASE_PORT=3306"

  # Web server
  web:
    container_name: ${COMPOSE_PROJECT_NAME}-web
    image: nginx:1.25.3
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-logs:/var/log/nginx
      # Inherit from app container
      - ..:/var/www/ba-sulu-intranet
      - ./app/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${WEB_PORT}:80
    links:
      - app:app

  # Database
  database:
    container_name: ${COMPOSE_PROJECT_NAME}-database
    image: mariadb:11.2.2
    volumes:
      - ./database:/var/lib/mysql_sulu
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  # PhpMyAdmin for database
  phpmyadmin-database:
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=database
      - UPLOAD_LIMIT=128M

volumes:
  app: {}
